# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: sumativa2dunfin
services:
  mssql:
    extends:
      file: ./mssql.yml
      service: mssql
    profiles:
      - ''
      - prod
